config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    root 'devise/sessions#new'
  end

  resources :users do
    resources :posts do
      resources :comments, only: %i[new create]
      resources :likes, only: %i[new create]
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
  after_save :update_comments_counter

  private

  def update_comments_counter
    post.update(comments_counter: post.comments.count)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post
  after_save :update_likes_counter

  private

  def update_likes_counter
    post.update(likes_counter: post.likes.count)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: :author_id
  has_many :likes, foreign_key: :post_id
  has_many :comments, foreign_key: :post_id
  after_save :update_post_counter

  validates :title, presence: true, length: { maximum: 250 }
  validates :comments_counter, numericality: { greater_than_or_equal_to: 0 }
  validates :likes_counter, numericality: { greater_than_or_equal_to: 0 }

  def recent_comments
    comments.order(created_at: :desc).limit(5)
  end

  private

  def update_post_counter
    author.update(posts_counter: author.posts.count)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  has_many :comments, foreign_key: :user_id
  has_many :likes, foreign_key: :user_id
  has_many :posts, foreign_key: :author_id

  validates :name, presence: true
  validates :posts_counter, numericality: { greater_than_or_equal_to: 0 }

  def recent_posts
    posts.order(created_at: :desc).limit(3)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def after_sign_in_path_for(_resource)
    users_path
  end

  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name bio photo])
  end

  def configure_devise_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |user|
      user.permit(:name, :bio, :email, :password, :password_confirmation, :photo)
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_user_and_post

  def new
    @comment = Comment.new
  end

  def create
    @comment = Comment.new(comment_params)
    @comment.user = current_user
    @comment.post = @post

    if @comment.save
      redirect_to user_post_path(@user, @post), notice: 'Comment created successfully.'
    else
      render :new
    end
  end

  private

  def set_user_and_post
    @user = User.find(params[:user_id])
    @post = Post.find(params[:post_id])
  end

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :set_user_and_post

  def new
    @like = Like.new
  end

  def create
    @like = Like.new(user: @current_user, post: @post)

    if @like.save
      redirect_to user_post_path(@user, @post), notice: 'Post liked successfully.'
    else
      render :new
    end
  end

  private

  def set_user_and_post
    @user = User.find(params[:user_id])
    @post = Post.find(params[:post_id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @user = User.find(params[:user_id])
    @posts = @user.posts.includes(:author, :comments, :likes).order(created_at: :desc).page(params[:page]).per(4)
  end

  def show
    @user = User.find(params[:user_id])
    @post = Post.find(params[:id])
    @like = Like.new
    @comment = Comment.new
  end

  def new
    @user = User.find(params[:user_id])
    @post = Post.new
  end

  def create
    @user = current_user
    @post = @user.posts.build(post_params)

    if @post.save
      redirect_to user_post_path(@user, @post), notice: 'Post created successfully.'
    else
      render :new
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all.order(created_at: :desc)
  end

  def show
    @user = User.find(params[:id])
    @posts = @user.posts
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/_form.html.erb
<%= form_with(model: [@user, @post, @comment], url: user_post_comments_path(@user, @post), method: :post, class: "w-75") do |form| %>
  <div class="d-flex flex-column gap-3 align-self-center">
  <h3 class="text-center">Add new comment in <%= @user.name %>'s post</h3>
  <div class="d-flex gap-3 w-100 align-items-center">
     <%= form.text_area :text, class: 'form-control border rounded-5 px-4 py-3 fs-3 w-100', required: true %>
  </div>

  <div class="actions text-center align-self-end">
    <%= form.submit 'Add Comment', class: "btn btn-primary fs-3 px-3 py-2 rounded-pill" %>
  </div>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
  </head>

  <body class="bg-light">
    <% if user_signed_in? %>
    <div class="d-flex align-items-end">
    <div class="mt-3 me-5 ms-auto d-flex align-items-center gap-3">
        <img class="rounded-circle bg-white p-1 border m-0 comment-profile-picture" src="<%= current_user.photo %>" alt="User Photo">
        <%= link_to current_user.name, user_path(current_user), class: "text-decoration-none fs-3" %>
        <%= button_to "Log Out", destroy_user_session_path, method: :delete, class: 'btn btn-primary fs-3 px-4 py-2 rounded-pill w-100' %>
      </div>
      </div>
    <% end %>
    <%= yield %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
  </body>
</html>

app/views/likes/_form.html.erb
<%= form_with(model: [@user, @post, @like], url: user_post_likes_path(@user, @post), method: :post) do |form| %>
  <div class="actions d-flex gap-3 align-items-center">
  <p class="mb-0 fs-5"><%= @post.comments.count %> Comments | <%= @post.likes.count %> Likes</p>
    <%= form.submit 'Like', class: 'btn btn-primary fs-3 px-5 py-2 rounded-pill' %>
  </div>
<% end %>

app/views/posts/index.html.erb
<div class="d-flex flex-column align-items-center gap-4 my-5">
    <div class="container d-flex w-75 p-0">
        <a href="<%= user_path(@user) %>">
            <img class="rounded-circle bg-white p-2 border me-4 profile-pic" src="<%= @user.photo %>" alt="User Photo">
        </a>
        <div class="border rounded-5 w-100 bg-white p-4 d-flex flex-column justify-content-between">
            <div class="w-25 m-0">
                <h2 class="text-decoration-none fs-2 text-decoration-underline-hover text-primary">
                    <%= link_to @user.name, user_path(@user), class: "text-decoration-none" %>
                </h2>
                <p class="user-posts text-end me-5 fs-5">Number of posts: <%= @user.posts_counter %></p>
            </div>
            <div class="align-self-end d-flex align-items-center gap-3">
                <% if current_user == @user %>
                    <%= link_to "Create New Post", new_user_post_path(@user), class: "btn btn-primary fs-3 px-4 py-2 rounded-pill" %>
                <% else %>
                    <%= link_to "User details", user_path(@user), class: "btn btn-primary fs-3 px-3 py-2 rounded-pill" %>
                <% end %>
                <%= link_to "Back to Home", root_path, title:"To Home Page", class: "text-decoration-none fs-4 text-decoration-underline-hover text-primary" %>
            </div>
        </div>
    </div>

    <div class="d-flex flex-column align-items-center gap-4 w-75">
        <div class="d-flex flex-column align-items-center gap-4 w-100">
            <% if @posts.count == 0 %>
                <h3 class="text-center">No posts yet</h3>
            <% else %>
                <% @posts.each do |post| %> 
                    <div class="border rounded-5 w-100 bg-white p-4">
                        <h3 class="mb-0">
                           <%= link_to post.title + " by " + @user.name,  user_post_path(user_id: @user.id, id: post.id), class: "text-decoration-none text-decoration-underline-hover" %>
                        </h3>
                        <span class="text-secondary">
                            Post no. <%= post.id %>
                        </span>
                        <p class="fs-3 my-3"><%= post.text %></p>
                        <div class="text-end">
                            <p class="mb-0 fs-5"><%= post.comments.count %> Comments | <%= post.likes.count %> Likes</p>
                        </div>
                        <% if post.comments.count > 0 %>
                            <div class="border w-75 mx-auto m-4 p-0 align-self-center"></div>
                            <h3 class="text-center m-0">Recent Comments</h3>
                            <div class="d-flex flex-column gap-3">
                                <% post.recent_comments.each do |comment| %>
                                    <div class="d-flex flex-column">
                                        <h4 class="mb-0">
                                            <img class="rounded-circle bg-white p-1 border m-0 comment-profile-picture" src="<%= comment.user.photo %>" alt="User Photo">
                                            <%= link_to comment.user.name, user_path(comment.user), class: "text-decoration-none text-decoration-underline-hover" %>
                                        </h4>
                                        <p class="fs-4 ms-5"><%= comment.text %></p>
                                    </div>
                                <% end %>
                            </div>
                            <div class="d-flex gap-3 align-self-center">
                                <%= link_to "See all comments",  user_post_path(user_id: @user.id, id: post.id), class: "text-decoration-none fs-4 text-decoration-underline-hover text-primary ms-auto" %>
                            </div>
                        <% end %> 
                    </div>
                <% end %>
            <% end %>
        </div>
        <div class="d-flex gap-3 align-self-center">
            <%= link_to "User details", user_path(@user), class: "btn btn-primary fs-3 px-3 py-2 rounded-pill" %>
            <%= link_to "Back to Home", root_path, class: "btn btn-primary fs-3 px-3 py-2 rounded-pill" %>
        </div>
        <div class="pagination">
        <%= paginate @posts, window: 2 %>
        <div>
    </div>
</div>

app/views/posts/new.html.erb
<%= form_with(model: [@user, @post], url: user_posts_path(@user), method: :post, class: "form") do |form| %>
<div class="d-flex flex-column mt-3">
  <h3 class="text-center m-3">Add New Post for <%= @user.name %></h3>
  <div class="d-flex flex-column gap-3 w-50 align-self-center">
    <div class="d-flex gap-3 w-100 align-items-center">
      <%= form.label :title, class: "fs-2" %>
      <%= form.text_field :title, class: "form-control border rounded-5 px-4 py-3 fs-3 w-100", required: true %>
    </div>
    <div class="d-flex gap-3 w-100 align-items-start">
      <%= form.label :text, class: "fs-2"%>
      <%= form.text_area :text, class: "form-control border rounded-5 px-4 py-3 fs-3 w-100", required: true %>
    </div>
    <div class="d-flex gap-3 justify-content-end">
      <%= link_to "Back to all posts", user_posts_path(@user), class: "text-decoration-none fs-4 text-decoration-underline-hover text-primary align-self-end my-auto" %>
      <%= form.submit 'Add New Post', class: "btn btn-primary fs-3 px-4 py-2 rounded-pill" %>
  </div>
<% end %>

app/views/posts/show.html.erb
<div class="d-flex flex-column align-items-center gap-4 my-5">
    <div class="container d-flex w-75 p-0">
        <a href="<%= user_path(@user) %>"><img class="rounded-circle bg-white p-2 border me-4 profile-pic" src="<%= @user.photo %>" alt="User Photo"></a>
        <div class="border rounded-5 w-100 bg-white p-4 d-flex flex-column justify-content-between">
            <div class="m-0">
                <h2 class="fs-2">
                    <%= @post.title %> by
                    <%= link_to @user.name, user_path(@user), class: "text-decoration-none text-decoration-underline-hover"  %>
                    </h2>
                <span class="text-secondary">Post no. <%= @post.id %></span>
                <p class="fs-3 my-3"><%= @post.text %></p>
            </div>
            <div class="d-flex flex-row gap-3 align-self-end">
                <%= render 'likes/form' %>
                <%= link_to "Back to Home", root_path, title:"To Home Page", class: "text-decoration-none fs-4 text-decoration-underline-hover text-primary my-auto" %>
            </div>
        </div>
    </div>

    <h3 class="text-center m-0">Comments</h3>
    <div class="d-flex flex-column gap-3 w-75 bg-white p-4 border rounded-5">
        <%if @post.comments.any? == false %>
            <p class="custom-border text-center fs-4 m-0">This post has no comments yet</p>
        <% else %>
        <% @post.comments.each do |comment| %>
            <div class="d-flex flex-column">
                <h4 class="mb-0">
                    <img class="rounded-circle bg-white p-1 border m-0 comment-profile-picture" src="<%= comment.user.photo %>" alt="User Photo">
                    <%= link_to comment.user.name, user_path(comment.user), class: "text-decoration-none text-decoration-underline-hover" %></h4>
                <p class="fs-4 ms-6"><%= comment.text %></p>
            </div>
        <% end %>
        <% end%>
    </div>

    <%= render 'comments/form' %>

    <%= link_to "Back to all posts", user_path(@user)+"/posts", class: "btn btn-primary fs-3 px-3 py-2 rounded-pill" %>
</div>

app/views/users/index.html.erb
  <div class="d-flex flex-column align-items-center gap-4 my-5">
  <% @users.each do |user| %>
    <div class="container d-flex w-75 p-0">
      <a href="<%= user_path(user) %>"><img class="rounded-circle bg-white p-2 border me-4 profile-pic" src="<%= user.photo %>" alt="User Photo"></a>
      <div class="border rounded-5 w-100 bg-white p-4 d-flex flex-column justify-content-between">
        <div class="w-25 m-0">
          <h2><%= link_to user.name, user_path(user), title:"To User Details", class: "text-decoration-none fs-2 text-decoration-underline-hover text-primary" %></h2>
          <p class="user-posts text-end me-5 fs-5">Number of posts: <%= user.posts_counter %></p>
        </div>
        <%= link_to "See details", user_path(user), title:"To User Details", class: "text-decoration-none fs-4 text-decoration-underline-hover text-primary align-self-end" %>
      </div>
    </div>
  <% end %>
  </div>

app/views/users/show.html.erb
    <div class="d-flex flex-column align-items-center gap-4 my-5">
        <div class="container d-flex w-75 p-0">
            <a href="<%= user_path(@user) %>">
                <img class="rounded-circle bg-white p-2 border me-4 profile-pic" src="<%= @user.photo %>" alt="User Photo">
            </a>
            <div class="border rounded-5 w-100 bg-white p-4 d-flex flex-column justify-content-between">
                <div class="w-25 m-0">
                    <h2 class="text-decoration-none fs-2 text-decoration-underline-hover text-primary">
                        <%= link_to @user.name, user_path(@user), class: "text-decoration-none" %>
                    </h2>
                    <p class="user-posts text-end me-5 fs-5">Number of posts: <%= @user.posts_counter %></p>
                </div>
                <div class="d-flex gap-3 align-self-end">
                    <%= link_to "See all posts", user_posts_path(@user), class: "btn btn-primary fs-3 px-3 py-2 rounded-pill" %>
                    <%= link_to "Back to Home", root_path, title:"To Home Page", class: "text-decoration-none fs-4 text-decoration-underline-hover text-primary align-self-end my-auto" %>
                </div>
            </div>
        </div>

        <div class="border rounded-5 w-75 bg-white p-4">
            <h2>Bio</h2>
            <p class="fs-3 mb-0"><%= @user.bio %></p>
        </div>

        <h3 class="text-center m-0">Recent Posts</h3>

        <div class="d-flex flex-column align-items-center gap-4 w-75">
            <% recent_posts = @user.recent_posts %>
            <% if recent_posts.any? %>
                <div class="d-flex flex-column align-items-center gap-4 w-100">
                    <% recent_posts.each do |post| %>
                        <div class="border rounded-5 w-100 bg-white p-4">
                            <h3 class="mb-0">
                                <%= link_to post.title + " by " + @user.name, user_post_path(user_id: @user.id, id: post.id), class: "text-decoration-none text-decoration-underline-hover" %>
                            </h3>
                            <span class="text-secondary">
                                Post no. <%= post.id %>
                            </span>
                            <p class="fs-3 my-3"><%= post.text %></p>
                            <div class="text-end">
                                <p class="mb-0 fs-5"><%= post.comments.count %> Comments | <%= post.likes.count %> Likes</p>
                            </div>
                        </div>
                    <% end %>
                </div>
            <% else %>
                <p class="custom-border py-2 text-center">No recent posts</p>
            <% end %>
            <div class="d-flex gap-3 align-self-center">
                <%= link_to "Back to home", users_path(@user), class: "btn btn-primary fs-3 px-3 py-2 rounded-pill" %>
                <%= link_to "See all posts", user_posts_path(@user), class: "btn btn-primary fs-3 px-3 py-2 rounded-pill" %>
            </div>
        </div>
    </div>